Update outlier_mnli.ipynb
elisno/outlier_mnli pull request #1
Opened 2022-11-05 05:25 UTC by paxF3E

Line777: list `mismatched_genres` is not defined.
list `genre_labels` would be the list instead, intuitively.

2022-11-05 13:06 UTC, elisno requested changes
Thank for the PR @paxF3E, I really appreciate it!

It looks like some code cells got out-of-sync when making the final edits for the article.

I made a suggestion with the correct fix.

2022-11-05 13:06 UTC, elisno commented on outlier_mnli.ipynb
> +    "    if genre in genre_labels:\n",
This subplot is a duplicate of an earlier label scatter plot to make an easier comparison with the cluster topics.

```suggestion
    "    if genre in mismatched_labels:\n",
```

In this block of code, it's intended to plot the genres in 
```python
mismatched_labels = {"nineeleven": 0, "facetoface": 1, "letters": 2, "oup": 3, "verbatim": 4}
```
with circle-markers. The `else` block handles the other genres.

2022-11-05 18:43 UTC, paxF3E commented on outlier_mnli.ipynb
> +    "    if genre in genre_labels:\n",
Ah alright. Couldnt figure `mismatched_labels` list earlier, but perfect now.

Also, the comparison with added topic clusters is very intuitive. I was startled to witness the extended application of HDBSCAN(clustering) and UMAP(dimensionality reduction) in this context, beyond the usual use cases :D

2022-11-05 18:50 UTC, elisno commented
@paxF3E, why did you close the PR? 😕 

You're correct that `mismatched_genres` isn't defined, but it was supposed to be `mismatched_labels`.

This still needs to be fixed, and I would gladly merge your PR if you commit the suggestion I just gave above. 🙂

2022-11-06 02:23 UTC, paxF3E commented
Kindly check if its good now :)

2022-11-06 13:37 UTC, elisno approved these changes
LGTM!

2022-11-06 13:42 UTC, merged